"""create charging stations and charge points

Revision ID: 11b18d6722e7
Revises: 49f82644800a
Create Date: 2026-08-07 19:59:26.735391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b18d6722e7'
down_revision = '49f82644800a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_stations',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_24_hours', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'maintenance', name='station_status'), server_default='draft', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('country_code = upper(country_code)', name=op.f('ck_charging_stations_country_code_uppercase')),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_charging_stations_valid_latitude')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_charging_stations_valid_longitude')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_charging_stations_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charging_stations'))
    )
    with op.batch_alter_table('charging_stations', schema=None) as batch_op:
        batch_op.create_index('ix_charging_stations_city_status', ['city', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_stations_owner_id'), ['owner_id'], unique=False)

    op.create_table('charge_points',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('connector_type', sa.Enum('ccs_2', 'type_2', 'chademo', 'gb_t', 'bharat_dc_001', name='connector_type'), nullable=False),
    sa.Column('power_type', sa.Enum('ac', 'dc', name='power_type'), nullable=False),
    sa.Column('max_power_kw', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.Enum('available', 'out_of_service', 'maintenance', 'retired', name='charge_point_status'), server_default='available', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_power_kw > 0', name=op.f('ck_charge_points_positive_max_power_kw')),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], name=op.f('fk_charge_points_station_id_charging_stations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charge_points')),
    sa.UniqueConstraint('station_id', 'code', name='station_code')
    )
    with op.batch_alter_table('charge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_points_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_points_station_id'))

    op.drop_table('charge_points')
    with op.batch_alter_table('charging_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charging_stations_owner_id'))
        batch_op.drop_index('ix_charging_stations_city_status')

    op.drop_table('charging_stations')

    # PostgreSQL enum types are separate schema objects. Dropping their tables
    # does not remove the types, so clean them up to keep downgrade/upgrade
    # cycles repeatable.
    sa.Enum(name='charge_point_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='power_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='connector_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='station_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
