"""add station management versions

Revision ID: 258cf6121335
Revises: bff01686c1c8
Create Date: 2026-08-08 19:15:53.158428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258cf6121335'
down_revision = 'bff01686c1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_check_constraint(batch_op.f('ck_charge_points_positive_version'), 'version > 0')

    with op.batch_alter_table('charging_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_check_constraint(batch_op.f('ck_charging_stations_positive_version'), 'version > 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_stations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_charging_stations_positive_version'), type_='check')
        batch_op.drop_column('version')

    with op.batch_alter_table('charge_points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_charge_points_positive_version'), type_='check')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
