"""add booking fees and payments

Revision ID: 7f0aa2673fae
Revises: c2b1ba3c8886
Create Date: 2026-08-08 17:04:09.542073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0aa2673fae'
down_revision = 'c2b1ba3c8886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('razorpay', name='payment_provider'), server_default='razorpay', nullable=False),
    sa.Column('status', sa.Enum('initiated', 'order_created', 'authorized', 'captured', 'failed', 'refunded', name='payment_status'), server_default='initiated', nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_subunits', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_positive_amount')),
    sa.CheckConstraint('amount_subunits > 0', name=op.f('ck_payments_positive_amount_subunits')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key')),
    sa.UniqueConstraint('provider_order_id', name=op.f('uq_payments_provider_order_id')),
    sa.UniqueConstraint('provider_payment_id', name=op.f('uq_payments_provider_payment_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_booking_status', ['booking_id', 'status'], unique=False)
        batch_op.create_index('ix_payments_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('charge_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_fee', sa.Numeric(precision=10, scale=2), server_default='50.00', nullable=False))
        batch_op.create_check_constraint(batch_op.f('ck_charge_points_non_negative_booking_fee'), 'booking_fee >= 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_charge_points_non_negative_booking_fee'), type_='check')
        batch_op.drop_column('booking_fee')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_user_created')
        batch_op.drop_index('ix_payments_booking_status')

    op.drop_table('payments')
    sa.Enum(name='payment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payment_provider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
