"""add payment refunds

Revision ID: 9a789f0119ea
Revises: df408d92b97e
Create Date: 2026-08-08 18:30:36.964172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a789f0119ea'
down_revision = 'df408d92b97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'pending', 'processed', 'failed', name='refund_status'), server_default='requested', nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_subunits', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('receipt', sa.String(length=40), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=100), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_positive_amount')),
    sa.CheckConstraint('amount_subunits > 0', name=op.f('ck_refunds_positive_amount_subunits')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_refunds_payment_id')),
    sa.UniqueConstraint('provider_refund_id', name=op.f('uq_refunds_provider_refund_id')),
    sa.UniqueConstraint('receipt', name=op.f('uq_refunds_receipt'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.execute('DROP TYPE IF EXISTS refund_status')
    # ### end Alembic commands ###
