"""add charging sessions

Revision ID: bff01686c1c8
Revises: 9a789f0119ea
Create Date: 2026-08-08 18:51:08.414688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff01686c1c8'
down_revision = '9a789f0119ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_sessions',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('charge_point_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'interrupted', name='charging_session_status'), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meter_start_kwh', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('meter_end_kwh', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('energy_consumed_kwh', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_charging_sessions_valid_end_time')),
    sa.CheckConstraint('energy_consumed_kwh IS NULL OR energy_consumed_kwh >= 0', name=op.f('ck_charging_sessions_non_negative_energy_consumed')),
    sa.CheckConstraint('meter_end_kwh IS NULL OR meter_end_kwh >= meter_start_kwh', name=op.f('ck_charging_sessions_valid_meter_end')),
    sa.CheckConstraint('meter_start_kwh >= 0', name=op.f('ck_charging_sessions_non_negative_meter_start')),
    sa.CheckConstraint('version > 0', name=op.f('ck_charging_sessions_positive_version')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_charging_sessions_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], name=op.f('fk_charging_sessions_charge_point_id_charge_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_charging_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charging_sessions')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_charging_sessions_booking_id'))
    )
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_charging_sessions_charge_point_status', ['charge_point_id', 'status'], unique=False)
        batch_op.create_index('ix_charging_sessions_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_charging_sessions_user_status')
        batch_op.drop_index('ix_charging_sessions_charge_point_status')

    op.drop_table('charging_sessions')
    op.execute('DROP TYPE IF EXISTS charging_session_status')
    # ### end Alembic commands ###
