"""create bookings table

Revision ID: c2b1ba3c8886
Revises: f69515989ba0
Create Date: 2026-08-08 16:46:34.421310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b1ba3c8886'
down_revision = 'f69515989ba0'
branch_labels = None
depends_on = None


def upgrade():
    # UUID equality needs the btree_gist operator class when it participates in
    # the same GiST exclusion constraint as a timestamp range.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('charge_point_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('held', 'payment_pending', 'confirmed', 'active', 'completed', 'cancelled', 'expired', name='booking_status'), server_default='held', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_bookings_positive_duration')),
    sa.CheckConstraint('total_amount IS NULL OR total_amount >= 0', name=op.f('ck_bookings_non_negative_total_amount')),
    sa.CheckConstraint('version > 0', name=op.f('ck_bookings_positive_version')),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], name=op.f('fk_bookings_charge_point_id_charge_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_charge_point_start', ['charge_point_id', 'starts_at'], unique=False)
        batch_op.create_index('ix_bookings_user_status', ['user_id', 'status'], unique=False)

    op.execute(
        """
        ALTER TABLE bookings
        ADD CONSTRAINT prevent_overlapping_bookings
        EXCLUDE USING gist (
            charge_point_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        )
        WHERE (
            status IN ('held', 'payment_pending', 'confirmed', 'active')
        )
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_user_status')
        batch_op.drop_index('ix_bookings_charge_point_start')

    op.drop_table('bookings')
    sa.Enum(name='booking_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
