"""add payment webhook events

Revision ID: df408d92b97e
Revises: 7f0aa2673fae
Create Date: 2026-08-08 17:44:12.674395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df408d92b97e'
down_revision = '7f0aa2673fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('provider', sa.String(length=30), server_default='razorpay', nullable=False),
    sa.Column('provider_event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('received', 'processed', 'ignored', name='webhook_event_status'), server_default='received', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_webhook_events')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_payment_webhook_events_provider_event_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_webhook_events')
    op.execute('DROP TYPE IF EXISTS webhook_event_status')
    # ### end Alembic commands ###
